config/routes.rb
Rails.application.routes.draw do
  get 'landing_page/index'
  get 'stories_feed', to: 'stories#stories_feed'

  resources :tags
  resources :stories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'stories#stories_feed'
end

app/models/story.rb
class Story
  include Mongoid::Document
  include Mongoid::Timestamps
  field :title, type: String
  field :content, type: String
  field :positive, type: Integer
  field :negative, type: Integer
  has_and_belongs_to_many :tags
end

app/models/tag.rb
class Tag
  include Mongoid::Document
  include Mongoid::Timestamps
  field :name, type: String
  field :description, type: String
  has_and_belongs_to_many :stories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  layout 'landing_page'
end

app/controllers/landing_page_controller.rb
class LandingPageController < ApplicationController
  def index
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: [:show, :edit, :update, :destroy]

  # GET /stories
  # GET /stories.json
  def index
    @stories = Story.all.order(updated_at: :desc)
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
  end

  # GET /stories/new
  def new
    @story = Story.new
  end

  # GET /stories/1/edit
  def edit
  end

  # POST /stories
  # POST /stories.json
  def create
    @story = Story.new(story_params)

    respond_to do |format|
      if @story.save
        format.html { redirect_to stories_path, notice: 'Story was successfully created.' }
        format.json { render :show, status: :created, location: @story }
      else
        format.html { render :new }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stories/1
  # PATCH/PUT /stories/1.json
  def update
    respond_to do |format|
      if @story.update(story_params)
        format.html { redirect_to @story, notice: 'Story was successfully updated.' }
        format.json { render :show, status: :ok, location: @story }
      else
        format.html { render :edit }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story.destroy
    respond_to do |format|
      format.html { redirect_to stories_url, notice: 'Story was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def stories_feed
    @stories = Story.all
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_story
    @story = Story.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def story_params
    params.require(:story).permit(:title, :content, :positive, :negative)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tag
    @tag = Tag.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def tag_params
    params.require(:tag).permit(:name, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/landing_page_helper.rb
module LandingPageHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/landing_page/index.html.haml
.page-header
  %h1
    Reflex.
    %small What do you learn today?
= link_to image_tag('login_with_facebook.jpg', id: 'login'), stories_feed_path
%blockquote#instruction
  %p#to_read{:align => "justify"}
    %em
      Every night before bed, I always...
      = link_to 'read more.',"#readmore", {'id' => 'link_to_read', 'data-toggle' => 'collapse'}
  %p#readmore.collapse{:align => "justify"}
    %em
      Every night before bed, I always recap what I have done during the day.
      I figure out something that I did wrong or failed to do.
      I need improvement and I don’t want to repeat the failure, so I note down commitment to change.
      In another day, I come back to my note to give credit to my commitment if I don’t repeat
      the failure or wrong thing again. Otherwise, I put a blame note to my commitment if I repeat
      the failure. With this habit, I can track  and see my personal growth insightfully so that
      I can improve myself and be motivated by what I have improved.
      %br/
      %br/
      With Reflex you can note your commitments, attach positive and negative note to them,
      track your personal growth, share it with your friends.
      = link_to 'Try it!', stories_feed_path
  %footer
    Reflex Team
    / <cite title="Source Title">Source Title</cite>

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    = render 'shared/header'

  %body
    .navbar.navbar-default.navbar-static-top
      .container
        %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand(href="#") Reflex
        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav
            %li= link_to "Link 1", "/path1"
            %li= link_to "Link 2", "/path2"
            %li= link_to "Link 3", "/path3"
            %li= link_to "Link 3", "/path3"

    .container
      .row
        .col-lg-9
          = bootstrap_flash
          = yield
        .col-lg-3
          .well.sidebar-nav
            %h3 Sidebar
            %ul.nav.nav-list
              %li.nav-header Sidebar
              %li= link_to "Link 1", "/path1"
              %li= link_to "Link 2", "/path2"
              %li= link_to "Link 3", "/path3"
      %footer
        = render 'shared/footer'

app/views/layouts/landing_page.html.haml
!!! 5
%html(lang="en")
  %head
    = render 'shared/header'

  %body
  .container-fluid
    .row
      .col-md-3
      .col-xs-12.col-sm-12.col-md-6
        = bootstrap_flash
        = yield
        %footer#copy_right
          = render 'shared/footer'
      .col-md-3

app/views/shared/_footer.html.haml
%p
  &copy; Reflex
  %span= Time.now.year

app/views/shared/_header.html.haml
%meta(charset="utf-8")
%meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
%meta(name="viewport" content="width=device-width, initial-scale=1.0")
%title= content_for?(:title) ? yield(:title) : "Reflex"
= csrf_meta_tags
= stylesheet_link_tag "application", :media => "all"
= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
= javascript_include_tag "application"
/ Le HTML5 shim, for IE6-8 support of HTML elements
/[if lt IE 9]
= javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"

app/views/stories/_form.html.haml
= simple_form_for @story, :html => { :class => 'form-horizontal' } do |f|
  = f.input :title
  = f.error_span :title
  = f.input :content
  = f.error_span :content
  = f.input :positive
  = f.error_span :positive
  = f.input :negative
  = f.error_span :negative
  = f.button :submit, :class => 'btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), stories_path, :class => 'btn btn-default'

app/views/stories/_modal_form.html.haml
#storyForm.modal.fade{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h4#myModalLabel.modal-title
          = locals[:form_name]
      = simple_form_for @story, remote: true, :html => { :class => 'form-horizontal' } do |f|
        .modal-body
          .form-group
            %label.control-label.col-sm-2{:for => "email"} Email:
            .col-sm-10
              -# %input#email.form-control{:placeholder => "Enter email", :type => "email"}
              = f.input :title, input_html: { class: 'form-control', width: '20%'  }, label: false

          = f.error_span :title
          = f.input :content
          = f.error_span :content
          = f.input :positive
          = f.error_span :positive
          = f.input :negative
          = f.error_span :negative
        .modal-footer
          -# %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Cancel
          -# %button.btn.btn-primary{:type => "button"} Save changes
          -# = link_to t('.cancel', :default => t("helpers.links.cancel")), stories_path, :class => 'btn btn-default'
          %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Cancel
          = f.button :submit, :class => 'btn-primary'

app/views/stories/_stories.html.haml
- @stories.each do |story|
  .panel.panel-primary
    .panel-heading
      .container-fluid
        .row
          .col_content.col-xs-10.col-sm-10.col-md-10
            %span.story_title
              = story.title
          .col_content.col-xs-2.col-sm-2.col-md-2
            .story_actions
              = link_to edit_story_path(story), :class => 'btn btn-default btn-xs' do
                %span.glyphicon.glyphicon-edit{"aria-hidden" => "true"}
              = link_to story_path(story), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-default btn-xs' do
                %span.glyphicon.glyphicon-trash{"aria-hidden" => "true"}
    .panel-body
      .story_tags
        - story.tags.each do |tags|
          tags.name
      .story_content
        = story.content
      %hr
      .container-fluid
        .row
          .col_content.col-xs-1.col-sm-1.col-md-1
            = link_to "#", :class => 'btn btn-default btn-xs' do
              %span.glyphicon.glyphicon-minus{"aria-hidden" => "true"}
          .col_content.col-xs-10.col-sm-10.col-md-10
            .progress
              .progress-bar.progress-bar-danger{:style => "width: 25%"}
              .progress-bar.progress-bar-success{:style => "width: 75%"}
          .col_content.col-xs-1.col-sm-1.col-md-1
            = link_to "#", :class => 'btn btn-default btn-xs' do
              %span.glyphicon.glyphicon-plus{"aria-hidden" => "true"}
      .story_timestamp
        .container-fluid
          .row
            .created_at.col-xs-6.col-sm-6.col-md-6
              %a{"data-container" => "body", "data-content" => "#{story.created_at.full_format(cookies[:fts_offset])}", "data-trigger" => "focus", "tabindex" => "0", "role" => "button", "data-placement" => "bottom", "data-toggle" => "popover"}
                = "Created at #{story.created_at.friendly_format}"
            .updated_at.col-xs-6.col-sm-6.col-md-6
              %a{"data-container" => "body", "data-content" => "#{story.updated_at.full_format(cookies[:fts_offset])}", "data-trigger" => "focus", "tabindex" => "0", "role" => "button", "data-placement" => "bottom", "data-toggle" => "popover"}
                = "Updated at #{story.updated_at.friendly_format}"

app/views/stories/edit.html.haml
- model_class = Story
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/stories/index.html.haml
- model_class = Story
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
= render partial: 'stories'
= link_to t('.new', :default => t("helpers.links.new"), :model => model_class.model_name.human.titleize), new_story_path, remote: true, :class => 'btn btn-primary'

app/views/stories/new.html.haml
- model_class = Story
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/stories/show.html.haml
- model_class = Story
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:title) + ':'
  %br
  = @story.title
%p
  %strong= model_class.human_attribute_name(:content) + ':'
  %br
  = @story.content
%p
  %strong= model_class.human_attribute_name(:positive) + ':'
  %br
  = @story.positive
%p
  %strong= model_class.human_attribute_name(:negative) + ':'
  %br
  = @story.negative


= link_to t('.back', :default => t("helpers.links.back")), stories_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_story_path(@story), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), story_path(@story), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/stories/stories_feed.html.haml
- model_class = Story
.page-header
  %h1#stories_feed_tl
    = t '.stories_feed', :default => t("helpers.title.stories_feed")
    %span.new_story_btn
      = link_to t('.new', :default => t("helpers.links.new"), :model => model_class.model_name.human.titleize), new_story_path, :class => 'btn btn-primary'

%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:title)
      %th= model_class.human_attribute_name(:content)
      %th= model_class.human_attribute_name(:positive)
      %th= model_class.human_attribute_name(:negative)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @stories.each do |story|
      %tr
        %td= link_to story.id, story_path(story)
        %td= story.title
        %td= story.content
        %td= story.positive
        %td= story.negative
        %td= story.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_story_path(story), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), story_path(story), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

app/views/tags/_form.html.haml
= simple_form_for @tag, :html => { :class => 'form-horizontal' } do |f|
  = f.input :name
  = f.error_span :name
  = f.input :description
  = f.error_span :description
  = f.button :submit, :class => 'btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), tags_path, :class => 'btn btn-default'

app/views/tags/edit.html.haml
- model_class = Tag
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/tags/index.html.haml
- model_class = Tag
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:description)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @tags.each do |tag|
      %tr
        %td= link_to tag.id, tag_path(tag)
        %td= tag.name
        %td= tag.description
        %td= tag.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_tag_path(tag), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), tag_path(tag), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_tag_path, :class => 'btn btn-primary'

app/views/tags/new.html.haml
- model_class = Tag
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/tags/show.html.haml
- model_class = Tag
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @tag.name
%p
  %strong= model_class.human_attribute_name(:description) + ':'
  %br
  = @tag.description


= link_to t('.back', :default => t("helpers.links.back")), tags_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_tag_path(@tag), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), tag_path(@tag), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'